-- ====================================================================
-- Seed data: All users, events, tickets, and checkins are created dynamically
-- through the application and authenticated APIs.
-- ====================================================================
